# Generated by Django 2.2 on 2019-08-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190727_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(choices=[('한식', '한식'), ('중식', '중식'), ('일식', '일식'), ('양식', '양식'), ('디저트', '디저트'), ('기타', '기타')], max_length=20),
        ),
    ]
