# Generated by Django 2.2 on 2019-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='menu',
            field=models.CharField(default=888, max_length=200),
            preserve_default=False,
        ),
    ]
